### ISSUE TITLE
heimdal 7.8: does not build with GCC 14+ because newlib's vasnprintf has an incompatible prototype (affects the native build too)

### ISSUE THREAD

**Issue by aswin-mcw** [Multicorewareinc/MSYS2-packages#43]
This is **not** a cross-compilation problem — it reproduces on a plain native build with the host's GCC 15.3.0.

newlib declares an incompatible `vasnprintf`:

```
/usr/include/stdio.h:318:  char *vasnprintf (char *, size_t *, const char *, __VALIST)
```

heimdal expects `int vasnprintf(char **, size_t, const char *, va_list)` and renames its own to `rk_vasnprintf` only when configure reports the system lacks one. The link test finds newlib's, so the rename is skipped and every call site fails:

```
snprintf.c:613:23: error: passing argument 1 of 'vasnprintf' from incompatible pointer type
snprintf.c:613:9:  error: assignment to 'int' from 'char *' makes integer from pointer without a cast
make[1]: *** [Makefile:1857: libtest_la-snprintf.lo] Error 1
```

`-Wincompatible-pointer-types` and `-Wint-conversion` became errors in GCC 14, so the shipped `heimdal 7.8.0-5` must predate that compiler. **The native recipe will hit this at its next rebuild.**

Fixed for the cross build in commit ea7aa3fd with `ac_cv_func_vasnprintf=no ac_cv_func_asnprintf=no`, which makes heimdal use its bundled implementation. The same two seeds fix the native build.

heimdal's vendored NetBSD libedit needs the same treatment (`wchar_t`/`wint_t` pointer mismatch, and `ioctl()` used without `<sys/ioctl.h>`), as does the standalone `libedit` package (commit 56ed469e).
